name: qr_utils_example
description: Demonstrates how to use the qr_utils plugin.
publish_to: 'none'

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  fluttertoast: ^3.1.3

  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  qr_utils:
    path: ../

flutter:

  uses-material-design: true

  assets:
    - assets/images/ic_no_image.png